//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class detail
    {
        public long DetailId { get; set; }
        public long CarId { get; set; }
        public double Speed { get; set; }
        public double Rpm { get; set; }
        public double EngineLoad { get; set; }
        public double Voltage { get; set; }
        public double Lon { get; set; }
        public double Lat { get; set; }
    
        [JsonIgnore]
        public virtual car car { get; set; }
    }
}
