//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Detail
    {
        public long DetailId { get; set; }
        public Nullable<long> CarId { get; set; }
        public Nullable<double> Speed { get; set; }
        public Nullable<double> Rpm { get; set; }
        public Nullable<double> EngineLoad { get; set; }
        public Nullable<double> Voltage { get; set; }
        public Nullable<double> Lon { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }

        [JsonIgnore]
        public virtual Car Car { get; set; }
    }
}
