//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public long ErrorId { get; set; }
        public Nullable<long> CarId { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorString { get; set; }
    
        public virtual car car { get; set; }
    }
}
